### PR TITLE
Fix branch hours

### PR DESCRIPTION
**Pull request by ggorlen**
The branch hour test is slow, so I'd be fine trimming it down or moving it to a separate file. I mostly wanted to verify that the code actually works for all the primary branches (now there are bookmobiles and so forth), and so I figured I'd leave the test in for now.

### CODE REVIEW

**Review by kajchang — APPROVED** [review]
Thanks! Reconfigured it a little to remove the old name -> id map because it's sort of extraneous now.

**Comment by kajchang** [comment]
Also published as version `1.5.4`.

**Comment by ggorlen** [comment]
Thanks! Isn't the branch id still needed for placing holds though? I haven't tried that functionality yet:

https://github.com/kajchang/SFPL/blob/master/sfpl/sfpl.py#L189

```py
resp = self.session.post(
    'https://sfpl.bibliocommons.com/holds/place_single_click_hold/{}'.format(book._id), data={
        'authenticity_token': BeautifulSoup(self.session.get('https://sfpl.bibliocommons.com/item/show/{}'.format(book._id)).text, 'lxml').find('input', {'name': 'authenticity_token'})['value'],
        'bib': book._id,
        'branch': branch._id # <---
    }, headers={
        'X-Requested-With': 'XMLHttpRequest',
        'Accept': 'application/json'
    })
```

**Comment by kajchang** [comment]
Oh shoot, forgot about that. Will fix

**Comment by kajchang** [comment]
Fixed!

**Pull request merged**
